import type { APIRoute } from 'astro';
import Anthropic from '@anthropic-ai/sdk';
import { rateLimit, getClientIp } from '@/lib/rateLimit';

export const prerender = false;

const MAX_BYTES = 50 * 1024;
const MAX_ENDPOINTS = 50;
const MODEL = 'claude-haiku-4-5';

const SYSTEM_PROMPT = `You convert a preprocessed HAR (HTTP Archive) summary into a typed TypeScript fetch SDK for a single API origin.

You receive a JSON object summarizing 1-N unique (method, normalized-path) endpoints from a single API. For each endpoint you see: the HTTP method, the URL pattern (path params replaced with :param), up to 3 sample request bodies, up to 3 sample response bodies, the set of header names observed (NO header values — values were stripped client-side and server-side for safety), the response status codes observed, and the query-string keys observed.

You return JSON only — never markdown, never commentary.

SEMANTIC METHOD NAMING (this is the differentiating intelligence — deterministic HAR-to-OpenAPI tools cannot do this):
- POST /v1/users + body {name, email} → createUser({name, email})
- GET /v1/users/:id → getUser(id)
- DELETE /v1/users/:id → deleteUser(id)
- PUT /v1/users/:id → updateUser(id, body)
- GET /v1/users → listUsers(params?)
- POST /v1/messages/send → sendMessage(...)
- POST /auth/login → login(...)
- Choose the verb based on HTTP method + path semantics + request body shape.
- camelCase. Singularize resource for single-item routes, pluralize for list routes.

RESOURCE GROUPING:
- Cluster endpoints sharing a top-level resource segment into a namespaced object:
  client.users.create() / client.users.get() / client.users.update() / client.users.list()
- The generated SDK class exposes these as properties of \`this.users\`, \`this.messages\`, etc.
- For a single-endpoint API, group under a single object based on the first path segment, or expose methods directly on the class — your call.

SAMPLE-MERGING + TYPE INFERENCE:
- Multiple samples for the same endpoint → merge into one method signature.
- Heterogeneous samples (one shows tags: [], another tags: ["foo"]) → tags: string[], not unknown.
- One sample shows email: null, another email: "x@y.z" → email: string | null.
- Query-string keys observed across samples → optional params object.
- Sample bodies are the source of truth for request/response types.

AUTH DETECTION:
- If every endpoint's observed headers include \`Authorization\` (any case) → the SDK class accepts \`{ apiKey: string }\` in its constructor and injects \`Authorization: Bearer \${apiKey}\` on every request.
- If the header is X-API-Key → inject as that header instead.
- If no auth header observed → no auth in constructor.
- NEVER include real auth values in the generated code — those were stripped server-side. Only the pattern.

BASE URL:
- Extract the common origin (scheme + host) from all endpoint URLs. Hard-code as \`private baseUrl = "https://api.example.com"\` on the class.
- If origins differ across endpoints, take the most common one and add a comment about the mixed origins.

OUTPUT FILE 1 — \`client\` (client.ts):
- Line 1: \`// Generated by har2sdk — edit freely\`
- Then the SDK class with constructor (apiKey if detected), private \`request<T>()\` helper using global \`fetch\`, and the namespaced resource methods.
- The request helper handles JSON encoding, header injection, and \`response.json()\` parsing. Throw on non-2xx with the response text.
- All public methods are async, return typed promises matching the response interfaces in types.ts.
- ALL types referenced from types.ts via \`import type { ... } from "./types";\` at the top.
- One trailing newline.

OUTPUT FILE 2 — \`types\` (types.ts):
- Line 1: \`// Generated by har2sdk — edit freely\`
- Then \`export interface\` declarations for every request body and every response body, named like \`CreateUserRequest\`, \`CreateUserResponse\`, \`GetUserResponse\`, etc.
- Use specific union literals when an enum-like field is visible.
- Use \`string | null\` for nullable fields. Use \`string[]\` not \`unknown[]\` when samples disambiguate.
- Group interfaces by resource with a \`// [Users]\` style comment header.
- One trailing newline.

OUTPUT FILE 3 — \`readme\` (README.md):
- Line 1: \`<!-- Generated by har2sdk — edit freely -->\`
- A short README with: a 2-line description, install hint (no npm package — paste both files into your repo), an "Authentication" section (if auth was detected) showing constructor usage, and **3 usage code examples** showing the most useful methods inferred from the HAR. Each example: a fenced TS block with \`import { Client } from "./client"; const client = new Client({ apiKey: "..." }); ...await client.users.create({...});\`. Realistic argument values based on the sample bodies.
- If hard caps truncated input, include a "Note: only N endpoints were synthesized; large HAR was sampled. Re-paste with a focused HAR for completeness." line.
- One trailing newline.

OUTPUT FORMAT: JSON only. Exact shape:
{"client": "<client.ts source as a single string>", "types": "<types.ts source as a single string>", "readme": "<README.md source as a single string>"}

Each string must be valid file contents (real newlines encoded as \\n inside the JSON). No \`any\`. No leading explanation. Output nothing but the JSON object.`;

type Out = { client: string; types: string; readme: string };

type SerializedEndpoint = {
  method: string;
  pathPattern: string;
  originalUrl: string;
  queryKeys: string[];
  headerNames: string[];
  statusCodes: number[];
  requestSamples: unknown[];
  responseSamples: unknown[];
};

type Endpoint = {
  method: string;
  pathPattern: string;
  originalUrl: string;
  queryKeys: Set<string>;
  headerNames: Set<string>;
  statusCodes: Set<number>;
  requestSamples: unknown[];
  responseSamples: unknown[];
};

type ParsedRequest =
  | { ok: false; status: number; error: string }
  | { ok: true; har: unknown; ip: string };

export const POST: APIRoute = async ({ request }) => {
  return await respond(await parseRequest(request));
};

async function parseRequest(request: Request): Promise<ParsedRequest> {
  const ip = getClientIp(request.headers);
  let body: unknown;
  try {
    body = await request.json();
  } catch {
    return { ok: false, status: 400, error: 'Body must be JSON.' };
  }
  if (!body || typeof body !== 'object' || typeof (body as any).har !== 'string') {
    return { ok: false, status: 400, error: 'Expected {"har": "<HAR JSON as string>"}.' };
  }
  const harText = (body as any).har as string;
  const bytes = new TextEncoder().encode(harText).length;
  if (bytes === 0) return { ok: false, status: 400, error: 'HAR input is empty.' };
  if (bytes > MAX_BYTES) {
    return {
      ok: false,
      status: 413,
      error: `HAR exceeds 50 KB (${bytes} bytes); truncating to 50 KB / 50 endpoints — paste a smaller export.`,
    };
  }
  let parsed: unknown;
  try {
    parsed = JSON.parse(harText);
  } catch {
    return {
      ok: false,
      status: 400,
      error: 'Could not parse HAR as JSON — make sure you exported a full HAR file from DevTools Network tab.',
    };
  }
  if (
    !parsed ||
    typeof parsed !== 'object' ||
    !(parsed as any).log ||
    !Array.isArray((parsed as any).log.entries)
  ) {
    return { ok: false, status: 400, error: 'Not a HAR file (missing log.entries array).' };
  }
  return { ok: true, har: parsed, ip };
}

async function respond(parsed: ParsedRequest): Promise<Response> {
  if (!parsed.ok) {
    return Response.json({ error: parsed.error }, { status: parsed.status });
  }
  const rl = rateLimit(parsed.ip);
  if (!rl.ok) {
    const mins = Math.ceil(rl.resetIn / 60000);
    return Response.json(
      { error: `You've hit 20 generations / hour. Try again in ~${mins}m.` },
      { status: 429 },
    );
  }
  const apiKey = process.env.ANTHROPIC_API_KEY || process.env.ANTHROPIC_AUTH_TOKEN || process.env.ANTHROPIC;
  if (!apiKey) {
    return Response.json(
      { error: 'Server misconfigured: ANTHROPIC key missing.' },
      { status: 500 },
    );
  }

  const summary = preprocessHar(parsed.har);
  if (summary.uniqueCount === 0) {
    return Response.json(
      { error: 'No HTTP entries found in HAR (log.entries was empty or all entries missing request data).' },
      { status: 400 },
    );
  }

  try {
    const out = await runClaude(apiKey, summary);
    const payload: Record<string, unknown> = {
      client: out.client,
      types: out.types,
      readme: out.readme,
      entryCount: summary.entryCount,
      uniqueCount: summary.uniqueCount,
    };
    if (summary.truncated) {
      payload.truncated = true;
      payload.originalEndpoints = summary.uniqueCount;
      payload.notice = `Input had ${summary.uniqueCount} endpoints; truncated to ${MAX_ENDPOINTS} — re-paste with a more focused HAR for completeness.`;
    }
    return Response.json(payload, {
      headers: { 'x-ratelimit-remaining': String(rl.remaining) },
    });
  } catch (e: any) {
    const msg = e?.message || 'LLM call failed';
    return Response.json({ error: msg }, { status: 502 });
  }
}

function normalizePath(url: string): string {
  let path: string;
  try {
    const u = new URL(url);
    path = u.pathname;
  } catch {
    // Fallback: strip scheme+host manually
    path = url.replace(/^[a-z]+:\/\/[^/]+/i, '').split('?')[0];
  }
  // strip trailing slash (but keep root "/")
  if (path.length > 1 && path.endsWith('/')) path = path.slice(0, -1);
  const segments = path.split('/').map((seg) => {
    if (!seg) return seg;
    // Pure-numeric segment
    if (/^\d+$/.test(seg)) return ':id';
    // UUID
    if (/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(seg)) return ':uuid';
    // Long hex hash
    if (/^[0-9a-f]{32,}$/i.test(seg)) return ':hash';
    return seg;
  });
  return segments.join('/');
}

function tryParseJson(text: string | undefined): unknown | undefined {
  if (!text) return undefined;
  try {
    return JSON.parse(text);
  } catch {
    return undefined;
  }
}

function isJsonMime(mime: string | undefined): boolean {
  if (!mime) return false;
  return /\/(json|.*\+json)\b/i.test(mime);
}

function preprocessHar(har: unknown): {
  endpoints: SerializedEndpoint[];
  truncated: boolean;
  entryCount: number;
  uniqueCount: number;
} {
  const entries: any[] = ((har as any)?.log?.entries) || [];
  const map = new Map<string, Endpoint>();

  for (const entry of entries) {
    const req = entry?.request;
    const resp = entry?.response;
    if (!req || typeof req.method !== 'string' || typeof req.url !== 'string') continue;
    const method = req.method.toUpperCase();
    const pathPattern = normalizePath(req.url);
    const key = `${method} ${pathPattern}`;

    let ep = map.get(key);
    if (!ep) {
      if (map.size >= MAX_ENDPOINTS) {
        // Don't add new endpoint groups beyond cap, but continue merging into existing ones.
        continue;
      }
      ep = {
        method,
        pathPattern,
        originalUrl: req.url,
        queryKeys: new Set<string>(),
        headerNames: new Set<string>(),
        statusCodes: new Set<number>(),
        requestSamples: [],
        responseSamples: [],
      };
      map.set(key, ep);
    }

    // Headers: names only.
    if (Array.isArray(req.headers)) {
      for (const h of req.headers) {
        if (h && typeof h.name === 'string') ep.headerNames.add(h.name);
      }
    }

    // Query keys.
    try {
      const u = new URL(req.url);
      for (const k of u.searchParams.keys()) ep.queryKeys.add(k);
    } catch {
      // ignore
    }
    if (Array.isArray(req.queryString)) {
      for (const q of req.queryString) {
        if (q && typeof q.name === 'string') ep.queryKeys.add(q.name);
      }
    }

    // Request body sample.
    if (req.postData && isJsonMime(req.postData.mimeType) && typeof req.postData.text === 'string') {
      const sample = tryParseJson(req.postData.text);
      if (sample !== undefined && ep.requestSamples.length < 3) {
        ep.requestSamples.push(sample);
      }
    }

    // Response.
    if (resp) {
      if (typeof resp.status === 'number') ep.statusCodes.add(resp.status);
      const content = resp.content;
      if (content && isJsonMime(content.mimeType) && typeof content.text === 'string') {
        const sample = tryParseJson(content.text);
        if (sample !== undefined && ep.responseSamples.length < 3) {
          ep.responseSamples.push(sample);
        }
      }
    }
  }

  // Count unique endpoints we *encountered* vs what fit in cap.
  // map.size is capped at MAX_ENDPOINTS. To know if we truncated, count unique keys
  // we *would* have stored.
  let totalUnique = 0;
  const seen = new Set<string>();
  for (const entry of entries) {
    const req = entry?.request;
    if (!req || typeof req.method !== 'string' || typeof req.url !== 'string') continue;
    const key = `${req.method.toUpperCase()} ${normalizePath(req.url)}`;
    if (!seen.has(key)) {
      seen.add(key);
      totalUnique += 1;
    }
  }

  const truncated = totalUnique > MAX_ENDPOINTS;

  const endpoints: SerializedEndpoint[] = Array.from(map.values()).map((ep) => ({
    method: ep.method,
    pathPattern: ep.pathPattern,
    originalUrl: ep.originalUrl,
    queryKeys: Array.from(ep.queryKeys),
    headerNames: Array.from(ep.headerNames),
    statusCodes: Array.from(ep.statusCodes),
    requestSamples: ep.requestSamples,
    responseSamples: ep.responseSamples,
  }));

  return {
    endpoints,
    truncated,
    entryCount: entries.length,
    uniqueCount: totalUnique,
  };
}

async function runClaude(
  apiKey: string,
  summary: { endpoints: SerializedEndpoint[]; truncated: boolean; entryCount: number; uniqueCount: number },
): Promise<Out> {
  const client = new Anthropic({ apiKey });
  const userText = JSON.stringify(
    {
      endpoints: summary.endpoints,
      truncated: summary.truncated,
      entryCount: summary.entryCount,
      uniqueCount: summary.uniqueCount,
    },
    null,
    2,
  );
  const msg = await client.messages.create({
    model: MODEL,
    max_tokens: 4096,
    system: SYSTEM_PROMPT,
    messages: [
      {
        role: 'user',
        content:
          'HAR summary (preprocessed; header values stripped):\n\n```json\n' +
          userText +
          '\n```\n\nReturn only the JSON object as specified.',
      },
    ],
  });
  const textBlock = msg.content.find((b) => b.type === 'text');
  if (!textBlock || textBlock.type !== 'text') {
    throw new Error('No text in model response.');
  }
  const raw = textBlock.text.trim();
  const parsed = extractJson(raw);
  if (
    !parsed ||
    typeof parsed.client !== 'string' ||
    typeof parsed.types !== 'string' ||
    typeof parsed.readme !== 'string'
  ) {
    throw new Error('Model returned malformed payload — try a smaller input or report at github.com/SolvoHQ/har2sdk/issues');
  }
  return {
    client: parsed.client.trim(),
    types: parsed.types.trim(),
    readme: parsed.readme.trim(),
  };
}

function extractJson(text: string): { client?: unknown; types?: unknown; readme?: unknown } | null {
  // Candidate set, tried in order:
  // 1. raw text as-is
  // 2. raw text without an outer ```json ... ``` wrapper (only if the WHOLE text
  //    is wrapped, otherwise we'd chop the nested fences inside the readme value)
  // 3. substring from first { to last }
  const candidates: string[] = [];
  const trimmed = text.trim();
  candidates.push(trimmed);

  // Outer-fence unwrap: only if text starts with ``` and ends with ```
  if (trimmed.startsWith('```')) {
    // Drop the opening fence (```json or ```)
    let inner = trimmed.replace(/^```[a-zA-Z]*\s*\n?/, '');
    // Drop trailing fence
    inner = inner.replace(/```\s*$/, '');
    candidates.push(inner.trim());
  }

  // First { to last } substring
  const start = trimmed.indexOf('{');
  const end = trimmed.lastIndexOf('}');
  if (start >= 0 && end > start) {
    candidates.push(trimmed.slice(start, end + 1));
  }

  for (const c of candidates) {
    try {
      const parsed = JSON.parse(c);
      if (parsed && typeof parsed === 'object') return parsed;
    } catch {
      // try next
    }
  }
  return null;
}
